FROM golang:1.17-alpine3.14 as builder
ENV CGO_ENABLED=0
WORKDIR /go/src/IoT
COPY . .
RUN go build -mod=vendor -o modbus-mqtt cmd/modbus-mqtt/main.go


FROM alpine:3.14
WORKDIR /
COPY --from=builder /go/src/IoT/modbus-mqtt .
RUN apk update && apk add ca-certificates

CMD ["/modbus-mqtt"]

