FROM golang:1.15 as builder
ENV CGO_ENABLED=0
WORKDIR /go/src/IoT
COPY . .
RUN go build -mod=vendor -o modbus-mqtt cmd/modbus-mqtt/main.go


FROM debian:bullseye-slim
WORKDIR /
COPY --from=builder /go/src/IoT/modbus-mqtt .
RUN apt-get update && apt-get install -yy ca-certificates

CMD ["/modbus-mqtt"]

