//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Power struct {
	Modtime time.Time `sql:"primary_key"`
	Solar   int32
	Total   int32
}
